'use strict'

// Archives roles to LC roles

module.exports = function (parent) {
  if (!parent.maps) parent.maps = {}

  parent.maps.archivesRoles = {
    'originator': 'cre',
    'contibutor': 'ctb',
    'actor': 'act',
	'adapter': 'adp',
	'addresse': 'rcp',
	'addressee': 'rcp',
	'annotator': 'ann',
	'arranger': 'arr',
	'artist': 'art',
	'associated name': 'asn',
	'author': 'aut',
	'author of introduction, etc': 'aui',
	'binder': 'bnd',
	'bookbinder': 'bnd',
	'choreographer': 'chr',
	'collaborator': 'ctb',
	'collector': 'col',
	'commentator': 'cmm',
	'compiler': 'com',
	'composer': 'cmp',
	'conductor': 'cnd',
	'contributor': 'ctb',
	'copyright holder': 'cph',
	'corrector': 'crr',
	'correspondent': 'crp',
	'costume designer': 'cst',
	'creator': 'cre',
	'dedicatee': 'dte',
	'dedicator': 'dto',
	'designer': 'dsr',
	'director': 'drt',
	'donor': 'dnr',
	'dubious author': 'dub',
	'editor': 'edt',
	'engraver': 'egr',
	'etcher': 'etr',
	'first party': 'fpy',
	'former owner': 'fmo',
	'funder': 'fnd',
	'host': 'hst',
	'ill': 'ill',
	'illustrator': 'ill',
	'inscriber': 'ins',
	'instrumentalist': 'itr',
	'interviewee': 'ive',
	'interviewer': 'ivr',
	'judge': 'jud',
	'librettist': 'lbt',
	'lyricist': 'lyr',
	'musician': 'mus',
	'narrator': 'nrt',
	'owner': 'own',
	'performer': 'prf',
	'photographer': 'pht',
	'plaintiff-appellant': 'pte',
	'printer': 'prt',
	'producer': 'pro',
	'production personnel': 'prd',
	'programmer': 'prg',
	'publisher': 'pbl',
	'recipeint': 'rcp',
	'recipient': 'rcp',
	'recording engineer': 'rce',
	'recpient': 'rcp',
	'scribe': 'scr',
	'sculptor': 'scl',
	'second party': 'spy',
	'secretary': 'sec',
	'signer': 'sgn',
	'speaker': 'spk',
	'sponsor': 'spn',
	'stage manager': 'stm',
	'supporting host': 'sht',
	'transcriber': 'trc',
	'translator': 'trl',
	'vocalist': 'sng',
	'witness': 'wit',
	'writer of accompanying material': 'wam'
  }
}