'use strict'

module.exports = function (parent) {
  if (!parent.labels) parent.labels = {}

  parent.labels.languages = {
    'aar': 'Afar',
    'abk': 'Abkhaz',
    'ace': 'Achinese',
    'ach': 'Acoli',
    'ada': 'Adangme',
    'ady': 'Adygei',
    'afa': 'Afroasiatic (Other)',
    'afh': 'Afrihili (Artificial language)',
    'afr': 'Afrikaans',
    'ain': 'Ainu',
    'aka': 'Akan',
    'akk': 'Akkadian',
    'alb': 'Albanian',
    'ale': 'Aleut',
    'alg': 'Algonquian (Other)',
    'alt': 'Altai',
    'amh': 'Amharic',
    'ang': 'English, Old (ca. 450-1100)',
    'anp': 'Angika',
    'apa': 'Apache languages',
    'ara': 'Arabic',
    'arc': 'Aramaic',
    'arg': 'Aragonese',
    'arm': 'Armenian',
    'arn': 'Mapuche',
    'arp': 'Arapaho',
    'art': 'Artificial (Other)',
    'arw': 'Arawak',
    'asm': 'Assamese',
    'ast': 'Bable',
    'ath': 'Athapascan (Other)',
    'aus': 'Australian languages',
    'ava': 'Avaric',
    'ave': 'Avestan',
    'awa': 'Awadhi',
    'aym': 'Aymara',
    'aze': 'Azerbaijani',
    'bad': 'Banda languages',
    'bai': 'Bamileke languages',
    'bak': 'Bashkir',
    'bal': 'Baluchi',
    'bam': 'Bambara',
    'ban': 'Balinese',
    'baq': 'Basque',
    'bas': 'Basa',
    'bat': 'Baltic (Other)',
    'bej': 'Beja',
    'bel': 'Belarusian',
    'bem': 'Bemba',
    'ben': 'Bengali',
    'ber': 'Berber (Other)',
    'bho': 'Bhojpuri',
    'bih': 'Bihari (Other)',
    'bik': 'Bikol',
    'bin': 'Edo',
    'bis': 'Bislama',
    'bla': 'Siksika',
    'bnt': 'Bantu (Other)',
    'bos': 'Bosnian',
    'bra': 'Braj',
    'bre': 'Breton',
    'btk': 'Batak',
    'bua': 'Buriat',
    'bug': 'Bugis',
    'bul': 'Bulgarian',
    'bur': 'Burmese',
    'byn': 'Bilin',
    'cad': 'Caddo',
    'cai': 'Central American Indian (Other)',
    'car': 'Carib',
    'cat': 'Catalan',
    'cau': 'Caucasian (Other)',
    'ceb': 'Cebuano',
    'cel': 'Celtic (Other)',
    'cha': 'Chamorro',
    'chb': 'Chibcha',
    'che': 'Chechen',
    'chg': 'Chagatai',
    'chi': 'Chinese',
    'chk': 'Chuukese',
    'chm': 'Mari',
    'chn': 'Chinook jargon',
    'cho': 'Choctaw',
    'chp': 'Chipewyan',
    'chr': 'Cherokee',
    'chu': 'Church Slavic',
    'chv': 'Chuvash',
    'chy': 'Cheyenne',
    'cmc': 'Chamic languages',
    'cop': 'Coptic',
    'cor': 'Cornish',
    'cos': 'Corsican',
    'cpe': 'Creoles and Pidgins, English-based (Other)',
    'cpf': 'Creoles and Pidgins, French-based (Other)',
    'cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
    'cre': 'Cree',
    'crh': 'Crimean Tatar',
    'crp': 'Creoles and Pidgins (Other)',
    'csb': 'Kashubian',
    'cus': 'Cushitic (Other)',
    'cze': 'Czech',
    'dak': 'Dakota',
    'dan': 'Danish',
    'dar': 'Dargwa',
    'day': 'Dayak',
    'del': 'Delaware',
    'den': 'Slavey',
    'dgr': 'Dogrib',
    'din': 'Dinka',
    'div': 'Divehi',
    'doi': 'Dogri',
    'dra': 'Dravidian (Other)',
    'dsb': 'Lower Sorbian',
    'dua': 'Duala',
    'dum': 'Dutch, Middle (ca. 1050-1350)',
    'dut': 'Dutch',
    'dyu': 'Dyula',
    'dzo': 'Dzongkha',
    'efi': 'Efik',
    'egy': 'Egyptian',
    'eka': 'Ekajuk',
    'elx': 'Elamite',
    'eng': 'English',
    'enm': 'English, Middle (1100-1500)',
    'epo': 'Esperanto',
    'est': 'Estonian',
    'ewe': 'Ewe',
    'ewo': 'Ewondo',
    'fan': 'Fang',
    'fao': 'Faroese',
    'fat': 'Fanti',
    'fij': 'Fijian',
    'fil': 'Filipino',
    'fin': 'Finnish',
    'fiu': 'Finno-Ugrian (Other)',
    'fon': 'Fon',
    'fre': 'French',
    'frm': 'French, Middle (ca. 1300-1600)',
    'fro': 'French, Old (ca. 842-1300)',
    'frr': 'North Frisian',
    'frs': 'East Frisian',
    'fry': 'Frisian',
    'ful': 'Fula',
    'fur': 'Friulian',
    'gaa': 'Gã',
    'gay': 'Gayo',
    'gba': 'Gbaya',
    'gem': 'Germanic (Other)',
    'geo': 'Georgian',
    'ger': 'German',
    'gez': 'Ethiopic',
    'gil': 'Gilbertese',
    'gla': 'Scottish Gaelic',
    'gle': 'Irish',
    'glg': 'Galician',
    'glv': 'Manx',
    'gmh': 'German, Middle High (ca. 1050-1500)',
    'goh': 'German, Old High (ca. 750-1050)',
    'gon': 'Gondi',
    'gor': 'Gorontalo',
    'got': 'Gothic',
    'grb': 'Grebo',
    'grc': 'Greek, Ancient (to 1453)',
    'gre': 'Greek, Modern (1453- )',
    'grn': 'Guarani',
    'gsw': 'Swiss German',
    'guj': 'Gujarati',
    'gwi': "Gwich'in",
    'hai': 'Haida',
    'hat': 'Haitian French Creole',
    'hau': 'Hausa',
    'haw': 'Hawaiian',
    'heb': 'Hebrew',
    'her': 'Herero',
    'hil': 'Hiligaynon',
    'him': 'Western Pahari languages',
    'hin': 'Hindi',
    'hit': 'Hittite',
    'hmn': 'Hmong',
    'hmo': 'Hiri Motu',
    'hrv': 'Croatian',
    'hsb': 'Upper Sorbian',
    'hun': 'Hungarian',
    'hup': 'Hupa',
    'iba': 'Iban',
    'ibo': 'Igbo',
    'ice': 'Icelandic',
    'ido': 'Ido',
    'iii': 'Sichuan Yi',
    'ijo': 'Ijo',
    'iku': 'Inuktitut',
    'ile': 'Interlingue',
    'ilo': 'Iloko',
    'ina': 'Interlingua (International Auxiliary Language Association)',
    'inc': 'Indic (Other)',
    'ind': 'Indonesian',
    'ine': 'Indo-European (Other)',
    'inh': 'Ingush',
    'ipk': 'Inupiaq',
    'ira': 'Iranian (Other)',
    'iro': 'Iroquoian (Other)',
    'ita': 'Italian',
    'jav': 'Javanese',
    'jbo': 'Lojban (Artificial language)',
    'jpn': 'Japanese',
    'jpr': 'Judeo-Persian',
    'jrb': 'Judeo-Arabic',
    'kaa': 'Kara-Kalpak',
    'kab': 'Kabyle',
    'kac': 'Kachin',
    'kal': 'Kalâtdlisut',
    'kam': 'Kamba',
    'kan': 'Kannada',
    'kar': 'Karen languages',
    'kas': 'Kashmiri',
    'kau': 'Kanuri',
    'kaw': 'Kawi',
    'kaz': 'Kazakh',
    'kbd': 'Kabardian',
    'kha': 'Khasi',
    'khi': 'Khoisan (Other)',
    'khm': 'Khmer',
    'kho': 'Khotanese',
    'kik': 'Kikuyu',
    'kin': 'Kinyarwanda',
    'kir': 'Kyrgyz',
    'kmb': 'Kimbundu',
    'kok': 'Konkani',
    'kom': 'Komi',
    'kon': 'Kongo',
    'kor': 'Korean',
    'kos': 'Kosraean',
    'kpe': 'Kpelle',
    'krc': 'Karachay-Balkar',
    'krl': 'Karelian',
    'kro': 'Kru (Other)',
    'kru': 'Kurukh',
    'kua': 'Kuanyama',
    'kum': 'Kumyk',
    'kur': 'Kurdish',
    'kut': 'Kootenai',
    'lad': 'Ladino',
    'lah': 'Lahndā',
    'lam': 'Lamba (Zambia and Congo)',
    'lao': 'Lao',
    'lat': 'Latin',
    'lav': 'Latvian',
    'lez': 'Lezgian',
    'lim': 'Limburgish',
    'lin': 'Lingala',
    'lit': 'Lithuanian',
    'lol': 'Mongo-Nkundu',
    'loz': 'Lozi',
    'ltz': 'Luxembourgish',
    'lua': 'Luba-Lulua',
    'lub': 'Luba-Katanga',
    'lug': 'Ganda',
    'lui': 'Luiseño',
    'lun': 'Lunda',
    'luo': 'Luo (Kenya and Tanzania)',
    'lus': 'Lushai',
    'mac': 'Macedonian',
    'mad': 'Madurese',
    'mag': 'Magahi',
    'mah': 'Marshallese',
    'mai': 'Maithili',
    'mak': 'Makasar',
    'mal': 'Malayalam',
    'man': 'Mandingo',
    'mao': 'Maori',
    'map': 'Austronesian (Other)',
    'mar': 'Marathi',
    'mas': 'Maasai',
    'may': 'Malay',
    'mdf': 'Moksha',
    'mdr': 'Mandar',
    'men': 'Mende',
    'mga': 'Irish, Middle (ca. 1100-1550)',
    'mic': 'Micmac',
    'min': 'Minangkabau',
    'mis': 'Miscellaneous languages',
    'mkh': 'Mon-Khmer (Other)',
    'mlg': 'Malagasy',
    'mlt': 'Maltese',
    'mnc': 'Manchu',
    'mni': 'Manipuri',
    'mno': 'Manobo languages',
    'moh': 'Mohawk',
    'mon': 'Mongolian',
    'mos': 'Mooré',
    'mul': 'Multiple languages',
    'mun': 'Munda (Other)',
    'mus': 'Creek',
    'mwl': 'Mirandese',
    'mwr': 'Marwari',
    'myn': 'Mayan languages',
    'myv': 'Erzya',
    'nah': 'Nahuatl',
    'nai': 'North American Indian (Other)',
    'nap': 'Neapolitan Italian',
    'nau': 'Nauru',
    'nav': 'Navajo',
    'nbl': 'Ndebele (South Africa)',
    'nde': 'Ndebele (Zimbabwe)',
    'ndo': 'Ndonga',
    'nds': 'Low German',
    'nep': 'Nepali',
    'new': 'Newari',
    'nia': 'Nias',
    'nic': 'Niger-Kordofanian (Other)',
    'niu': 'Niuean',
    'nno': 'Norwegian (Nynorsk)',
    'nob': 'Norwegian (Bokmål)',
    'nog': 'Nogai',
    'non': 'Old Norse',
    'nor': 'Norwegian',
    'nqo': "N'Ko",
    'nso': 'Northern Sotho',
    'nub': 'Nubian languages',
    'nwc': 'Newari, Old',
    'nya': 'Nyanja',
    'nym': 'Nyamwezi',
    'nyn': 'Nyankole',
    'nyo': 'Nyoro',
    'nzi': 'Nzima',
    'oci': 'Occitan (post-1500)',
    'oji': 'Ojibwa',
    'ori': 'Oriya',
    'orm': 'Oromo',
    'osa': 'Osage',
    'oss': 'Ossetic',
    'ota': 'Turkish, Ottoman',
    'oto': 'Otomian languages',
    'paa': 'Papuan (Other)',
    'pag': 'Pangasinan',
    'pal': 'Pahlavi',
    'pam': 'Pampanga',
    'pan': 'Panjabi',
    'pap': 'Papiamento',
    'pau': 'Palauan',
    'peo': 'Old Persian (ca. 600-400 B.C.)',
    'per': 'Persian',
    'phi': 'Philippine (Other)',
    'phn': 'Phoenician',
    'pli': 'Pali',
    'pol': 'Polish',
    'pon': 'Pohnpeian',
    'por': 'Portuguese',
    'pra': 'Prakrit languages',
    'pro': 'Provençal (to 1500)',
    'pus': 'Pushto',
    'que': 'Quechua',
    'raj': 'Rajasthani',
    'rap': 'Rapanui',
    'rar': 'Rarotongan',
    'roa': 'Romance (Other)',
    'roh': 'Raeto-Romance',
    'rom': 'Romani',
    'rum': 'Romanian',
    'run': 'Rundi',
    'rup': 'Aromanian',
    'rus': 'Russian',
    'sad': 'Sandawe',
    'sag': 'Sango (Ubangi Creole)',
    'sah': 'Yakut',
    'sai': 'South American Indian (Other)',
    'sal': 'Salishan languages',
    'sam': 'Samaritan Aramaic',
    'san': 'Sanskrit',
    'sas': 'Sasak',
    'sat': 'Santali',
    'scn': 'Sicilian Italian',
    'sco': 'Scots',
    'sel': 'Selkup',
    'sem': 'Semitic (Other)',
    'sga': 'Irish, Old (to 1100)',
    'sgn': 'Sign languages',
    'shn': 'Shan',
    'sid': 'Sidamo',
    'sin': 'Sinhalese',
    'sio': 'Siouan (Other)',
    'sit': 'Sino-Tibetan (Other)',
    'sla': 'Slavic (Other)',
    'slo': 'Slovak',
    'slv': 'Slovenian',
    'sma': 'Southern Sami',
    'sme': 'Northern Sami',
    'smi': 'Sami',
    'smj': 'Lule Sami',
    'smn': 'Inari Sami',
    'smo': 'Samoan',
    'sms': 'Skolt Sami',
    'sna': 'Shona',
    'snd': 'Sindhi',
    'snk': 'Soninke',
    'sog': 'Sogdian',
    'som': 'Somali',
    'son': 'Songhai',
    'sot': 'Sotho',
    'spa': 'Spanish',
    'srd': 'Sardinian',
    'srn': 'Sranan',
    'srp': 'Serbian',
    'srr': 'Serer',
    'ssa': 'Nilo-Saharan (Other)',
    'ssw': 'Swazi',
    'suk': 'Sukuma',
    'sun': 'Sundanese',
    'sus': 'Susu',
    'sux': 'Sumerian',
    'swa': 'Swahili',
    'swe': 'Swedish',
    'syc': 'Syriac',
    'syr': 'Syriac, Modern',
    'tah': 'Tahitian',
    'tai': 'Tai (Other)',
    'tam': 'Tamil',
    'tat': 'Tatar',
    'tel': 'Telugu',
    'tem': 'Temne',
    'ter': 'Terena',
    'tet': 'Tetum',
    'tgk': 'Tajik',
    'tgl': 'Tagalog',
    'tha': 'Thai',
    'tib': 'Tibetan',
    'tig': 'Tigré',
    'tir': 'Tigrinya',
    'tiv': 'Tiv',
    'tkl': 'Tokelauan',
    'tlh': 'Klingon (Artificial language)',
    'tli': 'Tlingit',
    'tmh': 'Tamashek',
    'tog': 'Tonga (Nyasa)',
    'ton': 'Tongan',
    'tpi': 'Tok Pisin',
    'tsi': 'Tsimshian',
    'tsn': 'Tswana',
    'tso': 'Tsonga',
    'tuk': 'Turkmen',
    'tum': 'Tumbuka',
    'tup': 'Tupi languages',
    'tur': 'Turkish',
    'tut': 'Altaic (Other)',
    'tvl': 'Tuvaluan',
    'twi': 'Twi',
    'tyv': 'Tuvinian',
    'udm': 'Udmurt',
    'uga': 'Ugaritic',
    'uig': 'Uighur',
    'ukr': 'Ukrainian',
    'umb': 'Umbundu',
    'und': 'Undetermined',
    'urd': 'Urdu',
    'uzb': 'Uzbek',
    'vai': 'Vai',
    'ven': 'Venda',
    'vie': 'Vietnamese',
    'vol': 'Volapük',
    'vot': 'Votic',
    'wak': 'Wakashan languages',
    'wal': 'Wolayta',
    'war': 'Waray',
    'was': 'Washoe',
    'wel': 'Welsh',
    'wen': 'Sorbian (Other)',
    'wln': 'Walloon',
    'wol': 'Wolof',
    'xal': 'Oirat',
    'xho': 'Xhosa',
    'yao': 'Yao (Africa)',
    'yap': 'Yapese',
    'yid': 'Yiddish',
    'yor': 'Yoruba',
    'ypk': 'Yupik languages',
    'zap': 'Zapotec',
    'zbl': 'Blissymbolics',
    'zen': 'Zenaga',
    'zha': 'Zhuang',
    'znd': 'Zande languages',
    'zul': 'Zulu',
    'zun': 'Zuni',
    'zxx': 'No linguistic content',
    'zza': 'Zaza',
    'language:aar': 'Afar',
    'language:abk': 'Abkhaz',
    'language:ace': 'Achinese',
    'language:ach': 'Acoli',
    'language:ada': 'Adangme',
    'language:ady': 'Adygei',
    'language:afa': 'Afroasiatic (Other)',
    'language:afh': 'Afrihili (Artificial language)',
    'language:afr': 'Afrikaans',
    'language:ain': 'Ainu',
    'language:aka': 'Akan',
    'language:akk': 'Akkadian',
    'language:alb': 'Albanian',
    'language:ale': 'Aleut',
    'language:alg': 'Algonquian (Other)',
    'language:alt': 'Altai',
    'language:amh': 'Amharic',
    'language:ang': 'English, Old (ca. 450-1100)',
    'language:anp': 'Angika',
    'language:apa': 'Apache languages',
    'language:ara': 'Arabic',
    'language:arc': 'Aramaic',
    'language:arg': 'Aragonese',
    'language:arm': 'Armenian',
    'language:arn': 'Mapuche',
    'language:arp': 'Arapaho',
    'language:art': 'Artificial (Other)',
    'language:arw': 'Arawak',
    'language:asm': 'Assamese',
    'language:ast': 'Bable',
    'language:ath': 'Athapascan (Other)',
    'language:aus': 'Australian languages',
    'language:ava': 'Avaric',
    'language:ave': 'Avestan',
    'language:awa': 'Awadhi',
    'language:aym': 'Aymara',
    'language:aze': 'Azerbaijani',
    'language:bad': 'Banda languages',
    'language:bai': 'Bamileke languages',
    'language:bak': 'Bashkir',
    'language:bal': 'Baluchi',
    'language:bam': 'Bambara',
    'language:ban': 'Balinese',
    'language:baq': 'Basque',
    'language:bas': 'Basa',
    'language:bat': 'Baltic (Other)',
    'language:bej': 'Beja',
    'language:bel': 'Belarusian',
    'language:bem': 'Bemba',
    'language:ben': 'Bengali',
    'language:ber': 'Berber (Other)',
    'language:bho': 'Bhojpuri',
    'language:bih': 'Bihari (Other)',
    'language:bik': 'Bikol',
    'language:bin': 'Edo',
    'language:bis': 'Bislama',
    'language:bla': 'Siksika',
    'language:bnt': 'Bantu (Other)',
    'language:bos': 'Bosnian',
    'language:bra': 'Braj',
    'language:bre': 'Breton',
    'language:btk': 'Batak',
    'language:bua': 'Buriat',
    'language:bug': 'Bugis',
    'language:bul': 'Bulgarian',
    'language:bur': 'Burmese',
    'language:byn': 'Bilin',
    'language:cad': 'Caddo',
    'language:cai': 'Central American Indian (Other)',
    'language:car': 'Carib',
    'language:cat': 'Catalan',
    'language:cau': 'Caucasian (Other)',
    'language:ceb': 'Cebuano',
    'language:cel': 'Celtic (Other)',
    'language:cha': 'Chamorro',
    'language:chb': 'Chibcha',
    'language:che': 'Chechen',
    'language:chg': 'Chagatai',
    'language:chi': 'Chinese',
    'language:chk': 'Chuukese',
    'language:chm': 'Mari',
    'language:chn': 'Chinook jargon',
    'language:cho': 'Choctaw',
    'language:chp': 'Chipewyan',
    'language:chr': 'Cherokee',
    'language:chu': 'Church Slavic',
    'language:chv': 'Chuvash',
    'language:chy': 'Cheyenne',
    'language:cmc': 'Chamic languages',
    'language:cop': 'Coptic',
    'language:cor': 'Cornish',
    'language:cos': 'Corsican',
    'language:cpe': 'Creoles and Pidgins, English-based (Other)',
    'language:cpf': 'Creoles and Pidgins, French-based (Other)',
    'language:cpp': 'Creoles and Pidgins, Portuguese-based (Other)',
    'language:cre': 'Cree',
    'language:crh': 'Crimean Tatar',
    'language:crp': 'Creoles and Pidgins (Other)',
    'language:csb': 'Kashubian',
    'language:cus': 'Cushitic (Other)',
    'language:cze': 'Czech',
    'language:dak': 'Dakota',
    'language:dan': 'Danish',
    'language:dar': 'Dargwa',
    'language:day': 'Dayak',
    'language:del': 'Delaware',
    'language:den': 'Slavey',
    'language:dgr': 'Dogrib',
    'language:din': 'Dinka',
    'language:div': 'Divehi',
    'language:doi': 'Dogri',
    'language:dra': 'Dravidian (Other)',
    'language:dsb': 'Lower Sorbian',
    'language:dua': 'Duala',
    'language:dum': 'Dutch, Middle (ca. 1050-1350)',
    'language:dut': 'Dutch',
    'language:dyu': 'Dyula',
    'language:dzo': 'Dzongkha',
    'language:efi': 'Efik',
    'language:egy': 'Egyptian',
    'language:eka': 'Ekajuk',
    'language:elx': 'Elamite',
    'language:eng': 'English',
    'language:enm': 'English, Middle (1100-1500)',
    'language:epo': 'Esperanto',
    'language:est': 'Estonian',
    'language:ewe': 'Ewe',
    'language:ewo': 'Ewondo',
    'language:fan': 'Fang',
    'language:fao': 'Faroese',
    'language:fat': 'Fanti',
    'language:fij': 'Fijian',
    'language:fil': 'Filipino',
    'language:fin': 'Finnish',
    'language:fiu': 'Finno-Ugrian (Other)',
    'language:fon': 'Fon',
    'language:fre': 'French',
    'language:frm': 'French, Middle (ca. 1300-1600)',
    'language:fro': 'French, Old (ca. 842-1300)',
    'language:frr': 'North Frisian',
    'language:frs': 'East Frisian',
    'language:fry': 'Frisian',
    'language:ful': 'Fula',
    'language:fur': 'Friulian',
    'language:gaa': 'Gã',
    'language:gay': 'Gayo',
    'language:gba': 'Gbaya',
    'language:gem': 'Germanic (Other)',
    'language:geo': 'Georgian',
    'language:ger': 'German',
    'language:gez': 'Ethiopic',
    'language:gil': 'Gilbertese',
    'language:gla': 'Scottish Gaelic',
    'language:gle': 'Irish',
    'language:glg': 'Galician',
    'language:glv': 'Manx',
    'language:gmh': 'German, Middle High (ca. 1050-1500)',
    'language:goh': 'German, Old High (ca. 750-1050)',
    'language:gon': 'Gondi',
    'language:gor': 'Gorontalo',
    'language:got': 'Gothic',
    'language:grb': 'Grebo',
    'language:grc': 'Greek, Ancient (to 1453)',
    'language:gre': 'Greek, Modern (1453- )',
    'language:grn': 'Guarani',
    'language:gsw': 'Swiss German',
    'language:guj': 'Gujarati',
    'language:gwi': "Gwich'in",
    'language:hai': 'Haida',
    'language:hat': 'Haitian French Creole',
    'language:hau': 'Hausa',
    'language:haw': 'Hawaiian',
    'language:heb': 'Hebrew',
    'language:her': 'Herero',
    'language:hil': 'Hiligaynon',
    'language:him': 'Western Pahari languages',
    'language:hin': 'Hindi',
    'language:hit': 'Hittite',
    'language:hmn': 'Hmong',
    'language:hmo': 'Hiri Motu',
    'language:hrv': 'Croatian',
    'language:hsb': 'Upper Sorbian',
    'language:hun': 'Hungarian',
    'language:hup': 'Hupa',
    'language:iba': 'Iban',
    'language:ibo': 'Igbo',
    'language:ice': 'Icelandic',
    'language:ido': 'Ido',
    'language:iii': 'Sichuan Yi',
    'language:ijo': 'Ijo',
    'language:iku': 'Inuktitut',
    'language:ile': 'Interlingue',
    'language:ilo': 'Iloko',
    'language:ina': 'Interlingua (International Auxiliary Language Association)',
    'language:inc': 'Indic (Other)',
    'language:ind': 'Indonesian',
    'language:ine': 'Indo-European (Other)',
    'language:inh': 'Ingush',
    'language:ipk': 'Inupiaq',
    'language:ira': 'Iranian (Other)',
    'language:iro': 'Iroquoian (Other)',
    'language:ita': 'Italian',
    'language:jav': 'Javanese',
    'language:jbo': 'Lojban (Artificial language)',
    'language:jpn': 'Japanese',
    'language:jpr': 'Judeo-Persian',
    'language:jrb': 'Judeo-Arabic',
    'language:kaa': 'Kara-Kalpak',
    'language:kab': 'Kabyle',
    'language:kac': 'Kachin',
    'language:kal': 'Kalâtdlisut',
    'language:kam': 'Kamba',
    'language:kan': 'Kannada',
    'language:kar': 'Karen languages',
    'language:kas': 'Kashmiri',
    'language:kau': 'Kanuri',
    'language:kaw': 'Kawi',
    'language:kaz': 'Kazakh',
    'language:kbd': 'Kabardian',
    'language:kha': 'Khasi',
    'language:khi': 'Khoisan (Other)',
    'language:khm': 'Khmer',
    'language:kho': 'Khotanese',
    'language:kik': 'Kikuyu',
    'language:kin': 'Kinyarwanda',
    'language:kir': 'Kyrgyz',
    'language:kmb': 'Kimbundu',
    'language:kok': 'Konkani',
    'language:kom': 'Komi',
    'language:kon': 'Kongo',
    'language:kor': 'Korean',
    'language:kos': 'Kosraean',
    'language:kpe': 'Kpelle',
    'language:krc': 'Karachay-Balkar',
    'language:krl': 'Karelian',
    'language:kro': 'Kru (Other)',
    'language:kru': 'Kurukh',
    'language:kua': 'Kuanyama',
    'language:kum': 'Kumyk',
    'language:kur': 'Kurdish',
    'language:kut': 'Kootenai',
    'language:lad': 'Ladino',
    'language:lah': 'Lahndā',
    'language:lam': 'Lamba (Zambia and Congo)',
    'language:lao': 'Lao',
    'language:lat': 'Latin',
    'language:lav': 'Latvian',
    'language:lez': 'Lezgian',
    'language:lim': 'Limburgish',
    'language:lin': 'Lingala',
    'language:lit': 'Lithuanian',
    'language:lol': 'Mongo-Nkundu',
    'language:loz': 'Lozi',
    'language:ltz': 'Luxembourgish',
    'language:lua': 'Luba-Lulua',
    'language:lub': 'Luba-Katanga',
    'language:lug': 'Ganda',
    'language:lui': 'Luiseño',
    'language:lun': 'Lunda',
    'language:luo': 'Luo (Kenya and Tanzania)',
    'language:lus': 'Lushai',
    'language:mac': 'Macedonian',
    'language:mad': 'Madurese',
    'language:mag': 'Magahi',
    'language:mah': 'Marshallese',
    'language:mai': 'Maithili',
    'language:mak': 'Makasar',
    'language:mal': 'Malayalam',
    'language:man': 'Mandingo',
    'language:mao': 'Maori',
    'language:map': 'Austronesian (Other)',
    'language:mar': 'Marathi',
    'language:mas': 'Maasai',
    'language:may': 'Malay',
    'language:mdf': 'Moksha',
    'language:mdr': 'Mandar',
    'language:men': 'Mende',
    'language:mga': 'Irish, Middle (ca. 1100-1550)',
    'language:mic': 'Micmac',
    'language:min': 'Minangkabau',
    'language:mis': 'Miscellaneous languages',
    'language:mkh': 'Mon-Khmer (Other)',
    'language:mlg': 'Malagasy',
    'language:mlt': 'Maltese',
    'language:mnc': 'Manchu',
    'language:mni': 'Manipuri',
    'language:mno': 'Manobo languages',
    'language:moh': 'Mohawk',
    'language:mon': 'Mongolian',
    'language:mos': 'Mooré',
    'language:mul': 'Multiple languages',
    'language:mun': 'Munda (Other)',
    'language:mus': 'Creek',
    'language:mwl': 'Mirandese',
    'language:mwr': 'Marwari',
    'language:myn': 'Mayan languages',
    'language:myv': 'Erzya',
    'language:nah': 'Nahuatl',
    'language:nai': 'North American Indian (Other)',
    'language:nap': 'Neapolitan Italian',
    'language:nau': 'Nauru',
    'language:nav': 'Navajo',
    'language:nbl': 'Ndebele (South Africa)',
    'language:nde': 'Ndebele (Zimbabwe)',
    'language:ndo': 'Ndonga',
    'language:nds': 'Low German',
    'language:nep': 'Nepali',
    'language:new': 'Newari',
    'language:nia': 'Nias',
    'language:nic': 'Niger-Kordofanian (Other)',
    'language:niu': 'Niuean',
    'language:nno': 'Norwegian (Nynorsk)',
    'language:nob': 'Norwegian (Bokmål)',
    'language:nog': 'Nogai',
    'language:non': 'Old Norse',
    'language:nor': 'Norwegian',
    'language:nqo': "N'Ko",
    'language:nso': 'Northern Sotho',
    'language:nub': 'Nubian languages',
    'language:nwc': 'Newari, Old',
    'language:nya': 'Nyanja',
    'language:nym': 'Nyamwezi',
    'language:nyn': 'Nyankole',
    'language:nyo': 'Nyoro',
    'language:nzi': 'Nzima',
    'language:oci': 'Occitan (post-1500)',
    'language:oji': 'Ojibwa',
    'language:ori': 'Oriya',
    'language:orm': 'Oromo',
    'language:osa': 'Osage',
    'language:oss': 'Ossetic',
    'language:ota': 'Turkish, Ottoman',
    'language:oto': 'Otomian languages',
    'language:paa': 'Papuan (Other)',
    'language:pag': 'Pangasinan',
    'language:pal': 'Pahlavi',
    'language:pam': 'Pampanga',
    'language:pan': 'Panjabi',
    'language:pap': 'Papiamento',
    'language:pau': 'Palauan',
    'language:peo': 'Old Persian (ca. 600-400 B.C.)',
    'language:per': 'Persian',
    'language:phi': 'Philippine (Other)',
    'language:phn': 'Phoenician',
    'language:pli': 'Pali',
    'language:pol': 'Polish',
    'language:pon': 'Pohnpeian',
    'language:por': 'Portuguese',
    'language:pra': 'Prakrit languages',
    'language:pro': 'Provençal (to 1500)',
    'language:pus': 'Pushto',
    'language:que': 'Quechua',
    'language:raj': 'Rajasthani',
    'language:rap': 'Rapanui',
    'language:rar': 'Rarotongan',
    'language:roa': 'Romance (Other)',
    'language:roh': 'Raeto-Romance',
    'language:rom': 'Romani',
    'language:rum': 'Romanian',
    'language:run': 'Rundi',
    'language:rup': 'Aromanian',
    'language:rus': 'Russian',
    'language:sad': 'Sandawe',
    'language:sag': 'Sango (Ubangi Creole)',
    'language:sah': 'Yakut',
    'language:sai': 'South American Indian (Other)',
    'language:sal': 'Salishan languages',
    'language:sam': 'Samaritan Aramaic',
    'language:san': 'Sanskrit',
    'language:sas': 'Sasak',
    'language:sat': 'Santali',
    'language:scn': 'Sicilian Italian',
    'language:sco': 'Scots',
    'language:sel': 'Selkup',
    'language:sem': 'Semitic (Other)',
    'language:sga': 'Irish, Old (to 1100)',
    'language:sgn': 'Sign languages',
    'language:shn': 'Shan',
    'language:sid': 'Sidamo',
    'language:sin': 'Sinhalese',
    'language:sio': 'Siouan (Other)',
    'language:sit': 'Sino-Tibetan (Other)',
    'language:sla': 'Slavic (Other)',
    'language:slo': 'Slovak',
    'language:slv': 'Slovenian',
    'language:sma': 'Southern Sami',
    'language:sme': 'Northern Sami',
    'language:smi': 'Sami',
    'language:smj': 'Lule Sami',
    'language:smn': 'Inari Sami',
    'language:smo': 'Samoan',
    'language:sms': 'Skolt Sami',
    'language:sna': 'Shona',
    'language:snd': 'Sindhi',
    'language:snk': 'Soninke',
    'language:sog': 'Sogdian',
    'language:som': 'Somali',
    'language:son': 'Songhai',
    'language:sot': 'Sotho',
    'language:spa': 'Spanish',
    'language:srd': 'Sardinian',
    'language:srn': 'Sranan',
    'language:srp': 'Serbian',
    'language:srr': 'Serer',
    'language:ssa': 'Nilo-Saharan (Other)',
    'language:ssw': 'Swazi',
    'language:suk': 'Sukuma',
    'language:sun': 'Sundanese',
    'language:sus': 'Susu',
    'language:sux': 'Sumerian',
    'language:swa': 'Swahili',
    'language:swe': 'Swedish',
    'language:syc': 'Syriac',
    'language:syr': 'Syriac, Modern',
    'language:tah': 'Tahitian',
    'language:tai': 'Tai (Other)',
    'language:tam': 'Tamil',
    'language:tat': 'Tatar',
    'language:tel': 'Telugu',
    'language:tem': 'Temne',
    'language:ter': 'Terena',
    'language:tet': 'Tetum',
    'language:tgk': 'Tajik',
    'language:tgl': 'Tagalog',
    'language:tha': 'Thai',
    'language:tib': 'Tibetan',
    'language:tig': 'Tigré',
    'language:tir': 'Tigrinya',
    'language:tiv': 'Tiv',
    'language:tkl': 'Tokelauan',
    'language:tlh': 'Klingon (Artificial language)',
    'language:tli': 'Tlingit',
    'language:tmh': 'Tamashek',
    'language:tog': 'Tonga (Nyasa)',
    'language:ton': 'Tongan',
    'language:tpi': 'Tok Pisin',
    'language:tsi': 'Tsimshian',
    'language:tsn': 'Tswana',
    'language:tso': 'Tsonga',
    'language:tuk': 'Turkmen',
    'language:tum': 'Tumbuka',
    'language:tup': 'Tupi languages',
    'language:tur': 'Turkish',
    'language:tut': 'Altaic (Other)',
    'language:tvl': 'Tuvaluan',
    'language:twi': 'Twi',
    'language:tyv': 'Tuvinian',
    'language:udm': 'Udmurt',
    'language:uga': 'Ugaritic',
    'language:uig': 'Uighur',
    'language:ukr': 'Ukrainian',
    'language:umb': 'Umbundu',
    'language:und': 'Undetermined',
    'language:urd': 'Urdu',
    'language:uzb': 'Uzbek',
    'language:vai': 'Vai',
    'language:ven': 'Venda',
    'language:vie': 'Vietnamese',
    'language:vol': 'Volapük',
    'language:vot': 'Votic',
    'language:wak': 'Wakashan languages',
    'language:wal': 'Wolayta',
    'language:war': 'Waray',
    'language:was': 'Washoe',
    'language:wel': 'Welsh',
    'language:wen': 'Sorbian (Other)',
    'language:wln': 'Walloon',
    'language:wol': 'Wolof',
    'language:xal': 'Oirat',
    'language:xho': 'Xhosa',
    'language:yao': 'Yao (Africa)',
    'language:yap': 'Yapese',
    'language:yid': 'Yiddish',
    'language:yor': 'Yoruba',
    'language:ypk': 'Yupik languages',
    'language:zap': 'Zapotec',
    'language:zbl': 'Blissymbolics',
    'language:zen': 'Zenaga',
    'language:zha': 'Zhuang',
    'language:znd': 'Zande languages',
    'language:zul': 'Zulu',
    'language:zun': 'Zuni',
    'language:zxx': 'No linguistic content',
    'language:zza': 'Zaza'
  }
}
