'use strict'

module.exports = function (parent) {
  if (!parent.labels) parent.labels = {}

  parent.labels.notes = {
    '500': 'General',
    '501': 'With',
    '502': 'Dissertation',
    '504': 'Bibliography, etc.',
    '505': 'Formatted Contents',
    '506': 'Restrictions on Access',
    '507': 'Scale Note for Graphic Material',
    '508': 'Creation/Production Credits',
    '510': 'Citation/References',
    '511': 'Participant or Performer',
    '513': 'Type of Report and Period Covered',
    '514': 'Data Quality',
    '515': 'Numbering Peculiarities',
    '516': 'Type of Computer File or Data',
    '518': 'Date/Time and Place of an Event',
    '521': 'Target Audience',
    '522': 'Geographic Coverage',
    '524': 'Preferred Citation of Described Materials',
    '525': 'Supplement',
    '526': 'Study Program Information',
    '530': 'Additional Physical Form available',
    '533': 'Reproduction',
    '534': 'Original Version',
    '535': 'Location of Originals/Duplicates',
    '536': 'Funding Information',
    '538': 'System Details',
    '540': 'Terms Governing Use and Reproduction',
    '541': 'Source of Acquisition',
    '542': 'Information Relating to Copyright Status',
    '544': 'Location of Other Archival Materials',
    '545': 'Biographical or Historical Data',
    '546': 'Language',
    '547': 'Former Title Complexity',
    '550': 'Issuing Body',
    '552': 'Entity and Attribute Information',
    '555': 'Cumulative Index/Finding Aids',
    '556': 'Information About Documentation',
    '561': 'Ownership and Custodial History',
    '562': 'Copy and Version Identification',
    '565': 'Case File Characteristics',
    '567': 'Methodology',
    '580': 'Linking Entry Complexity',
    '581': 'Publications About Described Materials',
    '583': 'Action',
    '584': 'Accumulation and Frequency of Use',
    '585': 'Exhibitions',
    '586': 'Awards',
    '588': 'Source of Description',
    '590': 'Local Note',
    'admin': 'Admin',
    'accrual method': 'Accrual Method',
    'accrual policy': 'Accrual Policy',
    'acqinfo': 'Source of Acquisition',
    'acquisition': 'Source of Acquisition',
    'action': 'Action',
    'additional physical form': 'Additional Physical Form available',
    'bibliographic history': 'General',
    'bibliography': 'Bibliography, etc.',
    'bioghist': 'Biographical or Historical Data',
    'biographical/historical': 'Biographical or Historical Data',
    'catrais': 'Catalog Raisonné',
    'chat': 'Chat',
    'citation/reference': 'Citation/References',
    'conservation history': 'Conservation History',
    'content': 'General',
    'creation/production credits': 'Creation/Production Credits',
    'creditline': 'Creation/Production Credits',
    'curatorialremarks': 'Curatorial Remarks',
    'custodhist': 'Ownership and Custodial History',
    'date': 'Date',
    'date/sequential designation': 'Date/Sequential Designation',
    'dateremarks': 'Date Remarks',
    'description': 'Description',
    'dimensions': 'Dimensions',
    'edition': 'Edition',
    'exhibitions': 'Exhibitions',
    'funding': 'Funding Information',
    'handwritten': 'Markings',
    'histattributions': 'Historical Attributions',
    'inscribed': 'Inscribed',
    'langmaterial': 'Language',
    'language': 'Language',
    'markings': 'Markings',
    'medium': 'Medium',
    'notes': 'General',
    'numbering': 'Numbering Peculiarities',
    'original location': 'Location of Originals/Duplicates',
    'original version': 'Original Version',
    'ownership': 'Ownership and Custodial History',
    'papersupport': 'Paper Support',
    'performers': 'Participant or Performer',
    'portfolio': 'Portfolio',
    'preferred citation': 'Preferred Citation of Described Materials',
    'provenance': 'Ownership and Custodial History',
    'publications': 'Publications About Described Materials',
    'pubreferences': 'Citation/References',
    'relatedmaterial': 'Related Material',
    'relatedworks': 'Related Works',
    'reproduction': 'Reproduction',
    'restriction': 'Restrictions on Access',
    'scopecontent': 'Scope and Content',
    'signed': 'Signed',
    'source characteristics': 'Source Characteristics',
    'source dimensions': 'Source Simensions',
    'source identifier': 'Source Identifier',
    'source note': 'Source',
    'source type': 'Source Type',
    'state': 'Copy and Version Identification',
    'statement of responsibility': 'Statement of Responsibility',
    'subject completeness': 'Subject Completeness',
    'system details': 'System Details',
    'thesis': 'Dissertation',
    'venue': 'Date/Time and Place of an Event',
    'version identification': 'Copy and Version Identification',
    '': 'Note',
    false: 'Note',
    null: 'Note'
  }
}
