'use strict'

module.exports = function (parent) {
  if (!parent.labels) parent.labels = {}

  parent.labels.relators = {
    'abr': 'Abridger',
    'acp': 'Art copyist',
    'act': 'Actor',
    'adi': 'Art director',
    'adp': 'Adapter',
    'aft': 'Author of afterword, colophon, etc.',
    'anl': 'Analyst',
    'anm': 'Animator',
    'ann': 'Annotator',
    'ant': 'Bibliographic antecedent',
    'ape': 'Appellee',
    'apl': 'Appellant',
    'app': 'Applicant',
    'aqt': 'Author in quotations or text abstracts',
    'arc': 'Architect',
    'ard': 'Artistic director',
    'arr': 'Arranger',
    'art': 'Artist',
    'asg': 'Assignee',
    'asn': 'Associated name',
    'ato': 'Autographer',
    'att': 'Attributed name',
    'auc': 'Auctioneer',
    'aud': 'Author of dialog',
    'aui': 'Author of introduction, etc.',
    'aus': 'Screenwriter',
    'aut': 'Author',
    'bdd': 'Binding designer',
    'bjd': 'Bookjacket designer',
    'bkd': 'Book designer',
    'bkp': 'Book producer',
    'blw': 'Blurb writer',
    'bnd': 'Binder',
    'bpd': 'Bookplate designer',
    'brd': 'Broadcaster',
    'brl': 'Braille embosser',
    'bsl': 'Bookseller',
    'cas': 'Caster',
    'ccp': 'Conceptor',
    'chr': 'Choreographer',
    'cli': 'Client',
    'cll': 'Calligrapher',
    'clr': 'Colorist',
    'clt': 'Collotyper',
    'cmm': 'Commentator',
    'cmp': 'Composer',
    'cmt': 'Compositor',
    'cnd': 'Conductor',
    'cng': 'Cinematographer',
    'cns': 'Censor',
    'coe': 'Contestant-appellee',
    'col': 'Collector',
    'com': 'Compiler',
    'con': 'Conservator',
    'cor': 'Collection registrar',
    'cos': 'Contestant',
    'cot': 'Contestant-appellant',
    'cou': 'Court governed',
    'cov': 'Cover designer',
    'cpc': 'Copyright claimant',
    'cpe': 'Complainant-appellee',
    'cph': 'Copyright holder',
    'cpl': 'Complainant',
    'cpt': 'Complainant-appellant',
    'cre': 'Creator',
    'crp': 'Correspondent',
    'crr': 'Corrector',
    'crt': 'Court reporter',
    'csl': 'Consultant',
    'csp': 'Consultant to a project',
    'cst': 'Costume designer',
    'ctb': 'Contributor',
    'cte': 'Contestee-appellee',
    'ctg': 'Cartographer',
    'ctr': 'Contractor',
    'cts': 'Contestee',
    'ctt': 'Contestee-appellant',
    'cur': 'Curator',
    'cwt': 'Commentator for written text',
    'dbp': 'Distribution place',
    'dfd': 'Defendant',
    'dfe': 'Defendant-appellee',
    'dft': 'Defendant-appellant',
    'dgg': 'Degree granting institution',
    'dgs': 'Degree supervisor',
    'dis': 'Dissertant',
    'dln': 'Delineator',
    'dnc': 'Dancer',
    'dnr': 'Donor',
    'dpc': 'Depicted',
    'dpt': 'Depositor',
    'drm': 'Draftsman',
    'drt': 'Director',
    'dsr': 'Designer',
    'dst': 'Distributor',
    'dtc': 'Data contributor',
    'dte': 'Dedicatee',
    'dtm': 'Data manager',
    'dto': 'Dedicator',
    'dub': 'Dubious author',
    'edc': 'Editor of compilation',
    'edm': 'Editor of moving image work',
    'edt': 'Editor',
    'egr': 'Engraver',
    'elg': 'Electrician',
    'elt': 'Electrotyper',
    'eng': 'Engineer',
    'enj': 'Enacting jurisdiction',
    'etr': 'Etcher',
    'evp': 'Event place',
    'exp': 'Expert',
    'fac': 'Facsimilist',
    'fds': 'Film distributor',
    'fld': 'Field director',
    'flm': 'Film editor',
    'fmd': 'Film director',
    'fmk': 'Filmmaker',
    'fmo': 'Former owner',
    'fmp': 'Film producer',
    'fnd': 'Funder',
    'fpy': 'First party',
    'frg': 'Forger',
    'gis': 'Geographic information specialist',
    'his': 'Host institution',
    'hnr': 'Honoree',
    'hst': 'Host',
    'ill': 'Illustrator',
    'ilu': 'Illuminator',
    'ins': 'Inscriber',
    'inv': 'Inventor',
    'isb': 'Issuing body',
    'itr': 'Instrumentalist',
    'ive': 'Interviewee',
    'ivr': 'Interviewer',
    'jud': 'Judge',
    'jug': 'Jurisdiction governed',
    'lbr': 'Laboratory',
    'lbt': 'Librettist',
    'ldr': 'Laboratory director',
    'led': 'Lead',
    'lee': 'Libelee-appellee',
    'lel': 'Libelee',
    'len': 'Lender',
    'let': 'Libelee-appellant',
    'lgd': 'Lighting designer',
    'lie': 'Libelant-appellee',
    'lil': 'Libelant',
    'lit': 'Libelant-appellant',
    'lsa': 'Landscape architect',
    'lse': 'Licensee',
    'lso': 'Licensor',
    'ltg': 'Lithographer',
    'lyr': 'Lyricist',
    'mcp': 'Music copyist',
    'mdc': 'Metadata contact',
    'med': 'Medium',
    'mfp': 'Manufacture place',
    'mfr': 'Manufacturer',
    'mod': 'Moderator',
    'mon': 'Monitor',
    'mrb': 'Marbler',
    'mrk': 'Markup editor',
    'msd': 'Musical director',
    'mte': 'Metal-engraver',
    'mtk': 'Minute taker',
    'mus': 'Musician',
    'nrt': 'Narrator',
    'opn': 'Opponent',
    'org': 'Originator',
    'orm': 'Organizer',
    'osp': 'Onscreen presenter',
    'oth': 'Other',
    'own': 'Owner',
    'pan': 'Panelist',
    'pat': 'Patron',
    'pbd': 'Publishing director',
    'pbl': 'Publisher',
    'pdr': 'Project director',
    'pfr': 'Proofreader',
    'pht': 'Photographer',
    'plt': 'Platemaker',
    'pma': 'Permitting agency',
    'pmn': 'Production manager',
    'pop': 'Printer of plates',
    'ppm': 'Papermaker',
    'ppt': 'Puppeteer',
    'pra': 'Praeses',
    'prc': 'Process contact',
    'prd': 'Production personnel',
    'pre': 'Presenter',
    'prf': 'Performer',
    'prg': 'Programmer',
    'prm': 'Printmaker',
    'prn': 'Production company',
    'pro': 'Producer',
    'prp': 'Production place',
    'prs': 'Production designer',
    'prt': 'Printer',
    'prv': 'Provider',
    'pta': 'Patent applicant',
    'pte': 'Plaintiff-appellee',
    'ptf': 'Plaintiff',
    'pth': 'Patent holder',
    'ptt': 'Plaintiff-appellant',
    'pup': 'Publication place',
    'rbr': 'Rubricator',
    'rcd': 'Recordist',
    'rce': 'Recording engineer',
    'rcp': 'Addressee',
    'rdd': 'Radio director',
    'red': 'Redaktor',
    'ren': 'Renderer',
    'res': 'Researcher',
    'rev': 'Reviewer',
    'rpc': 'Radio producer',
    'rps': 'Repository',
    'rpt': 'Reporter',
    'rpy': 'Responsible party',
    'rse': 'Respondent-appellee',
    'rsg': 'Restager',
    'rsp': 'Respondent',
    'rsr': 'Restorationist',
    'rst': 'Respondent-appellant',
    'rth': 'Research team head',
    'rtm': 'Research team member',
    'sad': 'Scientific advisor',
    'sce': 'Scenarist',
    'scl': 'Sculptor',
    'scr': 'Scribe',
    'sds': 'Sound designer',
    'sec': 'Secretary',
    'sgd': 'Stage director',
    'sgn': 'Signer',
    'sht': 'Supporting host',
    'sll': 'Seller',
    'sng': 'Singer',
    'spk': 'Speaker',
    'spn': 'Sponsor',
    'spy': 'Second party',
    'srv': 'Surveyor',
    'std': 'Set designer',
    'stg': 'Setting',
    'stl': 'Storyteller',
    'stm': 'Stage manager',
    'stn': 'Standards body',
    'str': 'Stereotyper',
    'tcd': 'Technical director',
    'tch': 'Teacher',
    'ths': 'Thesis advisor',
    'tld': 'Television director',
    'tlp': 'Television producer',
    'trc': 'Transcriber',
    'trl': 'Translator',
    'tyd': 'Type designer',
    'tyg': 'Typographer',
    'uvp': 'University place',
    'vac': 'Voice actor',
    'vdg': 'Videographer',
    'wac': 'Writer of added commentary',
    'wal': 'Writer of added lyrics',
    'wam': 'Writer of accompanying material',
    'wat': 'Writer of added text',
    'wdc': 'Woodcutter',
    'wde': 'Wood engraver',
    'win': 'Writer of introduction',
    'wit': 'Witness',
    'wpr': 'Writer of preface',
    'wst': 'Writer of supplementary textual content',
    'roles:-clb': 'Collaborator',
    'roles:-grt': 'Graphic technician',
    'roles:-voc': 'Vocalist',
    'roles:abr': 'Abridger',
    'roles:acp': 'Art copyist',
    'roles:act': 'Actor',
    'roles:adi': 'Art director',
    'roles:adp': 'Adapter',
    'roles:aft': 'Author of afterword, colophon, etc.',
    'roles:anl': 'Analyst',
    'roles:anm': 'Animator',
    'roles:ann': 'Annotator',
    'roles:ant': 'Bibliographic antecedent',
    'roles:ape': 'Appellee',
    'roles:apl': 'Appellant',
    'roles:app': 'Applicant',
    'roles:aqt': 'Author in quotations or text abstracts',
    'roles:arc': 'Architect',
    'roles:ard': 'Artistic director',
    'roles:arr': 'Arranger',
    'roles:art': 'Artist',
    'roles:asg': 'Assignee',
    'roles:asn': 'Associated name',
    'roles:ato': 'Autographer',
    'roles:att': 'Attributed name',
    'roles:auc': 'Auctioneer',
    'roles:aud': 'Author of dialog',
    'roles:aui': 'Author of introduction, etc.',
    'roles:aus': 'Screenwriter',
    'roles:aut': 'Author',
    'roles:bdd': 'Binding designer',
    'roles:bjd': 'Bookjacket designer',
    'roles:bkd': 'Book designer',
    'roles:bkp': 'Book producer',
    'roles:blw': 'Blurb writer',
    'roles:bnd': 'Binder',
    'roles:bpd': 'Bookplate designer',
    'roles:brd': 'Broadcaster',
    'roles:brl': 'Braille embosser',
    'roles:bsl': 'Bookseller',
    'roles:cas': 'Caster',
    'roles:ccp': 'Conceptor',
    'roles:chr': 'Choreographer',
    'roles:clb': 'Collaborator',
    'roles:cli': 'Client',
    'roles:cll': 'Calligrapher',
    'roles:clr': 'Colorist',
    'roles:clt': 'Collotyper',
    'roles:cmm': 'Commentator',
    'roles:cmp': 'Composer',
    'roles:cmt': 'Compositor',
    'roles:cnd': 'Conductor',
    'roles:cng': 'Cinematographer',
    'roles:cns': 'Censor',
    'roles:coe': 'Contestant-appellee',
    'roles:col': 'Collector',
    'roles:com': 'Compiler',
    'roles:con': 'Conservator',
    'roles:cor': 'Collection registrar',
    'roles:cos': 'Contestant',
    'roles:cot': 'Contestant-appellant',
    'roles:cou': 'Court governed',
    'roles:cov': 'Cover designer',
    'roles:cpc': 'Copyright claimant',
    'roles:cpe': 'Complainant-appellee',
    'roles:cph': 'Copyright holder',
    'roles:cpl': 'Complainant',
    'roles:cpt': 'Complainant-appellant',
    'roles:cre': 'Creator',
    'roles:crp': 'Correspondent',
    'roles:crr': 'Corrector',
    'roles:crt': 'Court reporter',
    'roles:csl': 'Consultant',
    'roles:csp': 'Consultant to a project',
    'roles:cst': 'Costume designer',
    'roles:ctb': 'Contributor',
    'roles:cte': 'Contestee-appellee',
    'roles:ctg': 'Cartographer',
    'roles:ctr': 'Contractor',
    'roles:cts': 'Contestee',
    'roles:ctt': 'Contestee-appellant',
    'roles:cur': 'Curator',
    'roles:cwt': 'Commentator for written text',
    'roles:dbp': 'Distribution place',
    'roles:dfd': 'Defendant',
    'roles:dfe': 'Defendant-appellee',
    'roles:dft': 'Defendant-appellant',
    'roles:dgg': 'Degree granting institution',
    'roles:dgs': 'Degree supervisor',
    'roles:dis': 'Dissertant',
    'roles:dln': 'Delineator',
    'roles:dnc': 'Dancer',
    'roles:dnr': 'Donor',
    'roles:dpc': 'Depicted',
    'roles:dpt': 'Depositor',
    'roles:drm': 'Draftsman',
    'roles:drt': 'Director',
    'roles:dsr': 'Designer',
    'roles:dst': 'Distributor',
    'roles:dtc': 'Data contributor',
    'roles:dte': 'Dedicatee',
    'roles:dtm': 'Data manager',
    'roles:dto': 'Dedicator',
    'roles:dub': 'Dubious author',
    'roles:edc': 'Editor of compilation',
    'roles:edm': 'Editor of moving image work',
    'roles:edt': 'Editor',
    'roles:egr': 'Engraver',
    'roles:elg': 'Electrician',
    'roles:elt': 'Electrotyper',
    'roles:eng': 'Engineer',
    'roles:enj': 'Enacting jurisdiction',
    'roles:etr': 'Etcher',
    'roles:evp': 'Event place',
    'roles:exp': 'Expert',
    'roles:fac': 'Facsimilist',
    'roles:fds': 'Film distributor',
    'roles:fld': 'Field director',
    'roles:flm': 'Film editor',
    'roles:fmd': 'Film director',
    'roles:fmk': 'Filmmaker',
    'roles:fmo': 'Former owner',
    'roles:fmp': 'Film producer',
    'roles:fnd': 'Funder',
    'roles:fpy': 'First party',
    'roles:frg': 'Forger',
    'roles:gis': 'Geographic information specialist',
    'roles:his': 'Host institution',
    'roles:hnr': 'Honoree',
    'roles:hst': 'Host',
    'roles:ill': 'Illustrator',
    'roles:ilu': 'Illuminator',
    'roles:ins': 'Inscriber',
    'roles:inv': 'Inventor',
    'roles:isb': 'Issuing body',
    'roles:itr': 'Instrumentalist',
    'roles:ive': 'Interviewee',
    'roles:ivr': 'Interviewer',
    'roles:jud': 'Judge',
    'roles:jug': 'Jurisdiction governed',
    'roles:lbr': 'Laboratory',
    'roles:lbt': 'Librettist',
    'roles:ldr': 'Laboratory director',
    'roles:led': 'Lead',
    'roles:lee': 'Libelee-appellee',
    'roles:lel': 'Libelee',
    'roles:len': 'Lender',
    'roles:let': 'Libelee-appellant',
    'roles:lgd': 'Lighting designer',
    'roles:lie': 'Libelant-appellee',
    'roles:lil': 'Libelant',
    'roles:lit': 'Libelant-appellant',
    'roles:lsa': 'Landscape architect',
    'roles:lse': 'Licensee',
    'roles:lso': 'Licensor',
    'roles:ltg': 'Lithographer',
    'roles:lyr': 'Lyricist',
    'roles:mcp': 'Music copyist',
    'roles:mdc': 'Metadata contact',
    'roles:med': 'Medium',
    'roles:mfp': 'Manufacture place',
    'roles:mfr': 'Manufacturer',
    'roles:mod': 'Moderator',
    'roles:mon': 'Monitor',
    'roles:mrb': 'Marbler',
    'roles:mrk': 'Markup editor',
    'roles:msd': 'Musical director',
    'roles:mte': 'Metal-engraver',
    'roles:mtk': 'Minute taker',
    'roles:mus': 'Musician',
    'roles:nrt': 'Narrator',
    'roles:opn': 'Opponent',
    'roles:org': 'Originator',
    'roles:orm': 'Organizer',
    'roles:osp': 'Onscreen presenter',
    'roles:oth': 'Other',
    'roles:own': 'Owner',
    'roles:pan': 'Panelist',
    'roles:pat': 'Patron',
    'roles:pbd': 'Publishing director',
    'roles:pbl': 'Publisher',
    'roles:pdr': 'Project director',
    'roles:pfr': 'Proofreader',
    'roles:pht': 'Photographer',
    'roles:plt': 'Platemaker',
    'roles:pma': 'Permitting agency',
    'roles:pmn': 'Production manager',
    'roles:pop': 'Printer of plates',
    'roles:ppm': 'Papermaker',
    'roles:ppt': 'Puppeteer',
    'roles:pra': 'Praeses',
    'roles:prc': 'Process contact',
    'roles:prd': 'Production personnel',
    'roles:pre': 'Presenter',
    'roles:prf': 'Performer',
    'roles:prg': 'Programmer',
    'roles:prm': 'Printmaker',
    'roles:prn': 'Production company',
    'roles:pro': 'Producer',
    'roles:prp': 'Production place',
    'roles:prs': 'Production designer',
    'roles:prt': 'Printer',
    'roles:prv': 'Provider',
    'roles:pta': 'Patent applicant',
    'roles:pte': 'Plaintiff-appellee',
    'roles:ptf': 'Plaintiff',
    'roles:pth': 'Patent holder',
    'roles:ptt': 'Plaintiff-appellant',
    'roles:pup': 'Publication place',
    'roles:rbr': 'Rubricator',
    'roles:rcd': 'Recordist',
    'roles:rce': 'Recording engineer',
    'roles:rcp': 'Addressee',
    'roles:rdd': 'Radio director',
    'roles:red': 'Redaktor',
    'roles:ren': 'Renderer',
    'roles:res': 'Researcher',
    'roles:rev': 'Reviewer',
    'roles:rpc': 'Radio producer',
    'roles:rps': 'Repository',
    'roles:rpt': 'Reporter',
    'roles:rpy': 'Responsible party',
    'roles:rse': 'Respondent-appellee',
    'roles:rsg': 'Restager',
    'roles:rsp': 'Respondent',
    'roles:rsr': 'Restorationist',
    'roles:rst': 'Respondent-appellant',
    'roles:rth': 'Research team head',
    'roles:rtm': 'Research team member',
    'roles:sad': 'Scientific advisor',
    'roles:sce': 'Scenarist',
    'roles:scl': 'Sculptor',
    'roles:scr': 'Scribe',
    'roles:sds': 'Sound designer',
    'roles:sec': 'Secretary',
    'roles:sgd': 'Stage director',
    'roles:sgn': 'Signer',
    'roles:sht': 'Supporting host',
    'roles:sll': 'Seller',
    'roles:sng': 'Singer',
    'roles:spk': 'Speaker',
    'roles:spn': 'Sponsor',
    'roles:spy': 'Second party',
    'roles:srv': 'Surveyor',
    'roles:std': 'Set designer',
    'roles:stg': 'Setting',
    'roles:stl': 'Storyteller',
    'roles:stm': 'Stage manager',
    'roles:stn': 'Standards body',
    'roles:str': 'Stereotyper',
    'roles:tcd': 'Technical director',
    'roles:tch': 'Teacher',
    'roles:ths': 'Thesis advisor',
    'roles:tld': 'Television director',
    'roles:tlp': 'Television producer',
    'roles:trc': 'Transcriber',
    'roles:trl': 'Translator',
    'roles:tyd': 'Type designer',
    'roles:tyg': 'Typographer',
    'roles:uvp': 'University place',
    'roles:vac': 'Voice actor',
    'roles:vdg': 'Videographer',
    'roles:wac': 'Writer of added commentary',
    'roles:wal': 'Writer of added lyrics',
    'roles:wam': 'Writer of accompanying material',
    'roles:wat': 'Writer of added text',
    'roles:wdc': 'Woodcutter',
    'roles:wde': 'Wood engraver',
    'roles:win': 'Writer of introduction',
    'roles:wit': 'Witness',
    'roles:wpr': 'Writer of preface',
    'roles:wst': 'Writer of supplementary textual content'
  }
}
